# Generated by Django 5.1.6 on 2025-02-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('department', models.CharField(max_length=150)),
                ('doctor', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
    ]
