# Generated by Django 5.1.6 on 2025-03-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_alter_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
